version: '3'

services:
  redis:
    image: redis:alpine
    container_name : "pjoterparker-redis"
    ports:
      - "6379:6379"
  eventStore:
    image: eventstore/eventstore:latest
    container_name : "pjoterparker-eventStore"
    ports:
     - 1113:1113
     - 2113:2113
  sql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name : "pjoterparker-sql"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA : "Y"
      SA_PASSWORD : "KQlqqjercDE7d4YSF3O"