version: '3'

services:
  redis:
    image: redis:alpine
    container_name : "pjoterparker-redis"
    ports:
      - "6379:6379"
    volumes :
      - pjoterparker-data:/var/lib/redis/data
    networks :
      - backend
  eventStore:
    image: eventstore/eventstore:latest
    container_name : "pjoterparker-eventStore"
    ports:
      - 1113:1113
      - 2113:2113
    volumes :
      - pjoterparker-data:/var/lib/eventstore/data
    networks :
      - backend
  sql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name : "pjoterparker-sql"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA : "Y"
      SA_PASSWORD : "KQlqqjercDE7d4YSF3O"
    volumes :
     - pjoterparker-data:/var/lib/db/data
    networks :
      - backend
  seq:
    image: datalust/seq:latest
    container_name: "pjoterparker-seq"
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA : "Y"
    volumes :
     - pjoterparker-data:/var/lib/seq/data
    networks :
      - backend
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "pjoterparker-rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes :
     - pjoterparker-data:/var/lib/rabbitmq/data
    networks :
      - backend
  sonarqube:
    image: sonarqube:latest
    container_name: "pjoterparker-sonarqube"
    ports:
      - "9000:9000"
    volumes :
     - pjoterparker-data:/opt/sonarqube/data
     - pjoterparker-data:/opt/sonarqube/logs
     - pjoterparker-data:/opt/sonarqube/extensions
    networks :
      - backend

volumes:
  pjoterparker-data:

networks:
  backend: