// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace PjoterParker.Api.Database.Migrations
{
    [DbContext(typeof(ApiDatabaseContext))]
    [Migration("20190926130739_AddSpotTable")]
    public partial class AddSpotTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PjoterParker.Api.Database.Entities.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("LocationId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("PjoterParker.Api.Database.Entities.Spot", b =>
                {
                    b.Property<Guid>("SpotId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("LocationId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<Guid?>("UserId");

                    b.HasKey("SpotId");

                    b.HasIndex("LocationId");

                    b.ToTable("Spot");
                });

            modelBuilder.Entity("PjoterParker.Api.Database.Entities.UniquenessTable", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(1024);

                    b.Property<string>("Value")
                        .HasMaxLength(1024);

                    b.Property<Guid>("AggrageteId");

                    b.HasKey("Key", "Value", "AggrageteId");

                    b.ToTable("UniquenessTable");
                });

            modelBuilder.Entity("PjoterParker.Api.Database.Entities.Spot", b =>
                {
                    b.HasOne("PjoterParker.Api.Database.Entities.Location", "Location")
                        .WithMany("Spots")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
        }
    }
}
